services:
  redis:
    image: redis:7
    container_name: snapfolia-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: snapfolia-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api:
    build: ./api
    container_name: snapfolia-api
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      UPLOAD_DIR: /volumes/images
    volumes:
      - ./volumes/images:/volumes/images
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  detection:
    build: ./detection-yolo
    container_name: snapfolia-detection
    environment:
      REDIS_URL: redis://redis:6379/0
      YOLO_MODEL_PATH: /app/models/best.pt
      UPLOAD_DIR: /volumes/images
    volumes:
      - ./volumes/images:/volumes/images
      - yolo_data:/app/models:ro
    depends_on:
      - redis
      - yolo-loader
    
  classification:
    build: ./classification-yolocls
    container_name: snapfolia-classification
    environment:
      REDIS_URL: redis://redis:6379/0
      YOLO_CLS_MODEL_PATH: /app/models/best.pt
      UPLOAD_DIR: /volumes/images
    volumes:
      - ./volumes/images:/volumes/images
      - yolo_cls_data:/app/models:ro
    depends_on:
      - redis
      - yolo-cls-loader

  yolo-loader:
    build: ./models/yolo-cuda11.8
    container_name: snapfolia-yolo-loader
    volumes:
      - yolo_data:/models
    command: "true"
  yolo-cls-loader:
    build: ./models/yolo-cls-cuda11.8
    container_name: snapfolia-yolo-cls-loader
    volumes:
      - yolo_cls_data:/models
    command: "true"

volumes:
  redis_data:
  yolo_data:
  yolo_cls_data:
