CLASS_MAP = {
    0: "Acacia",
    1: "African Talisay",
    2: "Aherns Balok",
    3: "Alagao",
    4: "Alibangbang",
    5: "Amugis",
    6: "Antipolo",
    7: "Apitong",
    8: "Asis",
    9: "Balayong",
    10: "Balete",
    11: "Banaba",
    12: "Bani",
    13: "Banuyo",
    14: "Barako",
    15: "Bayabas",
    16: "Betis",
    17: "Binunga",
    18: "Bolong-eta",
    19: "Dao",
    20: "Dita",
    21: "Duhat",
    22: "Eucalyptus",
    23: "Guyabano",
    24: "Hinadyong",
    25: "Ilang-Ilang",
    26: "Inyam",
    27: "Ipil",
    28: "Kalantas",
    29: "Kalingag",
    30: "Kalios",
    31: "Kamagong",
    32: "Katmon-Bayani",
    33: "Kayumanis",
    34: "Kulatingan",
    35: "Langka",
    36: "Lansones",
    37: "Lipote",
    38: "Madre-Cacao",
    39: "Mahogany",
    40: "Malabulak",
    41: "Malak Malak",
    42: "Malugai",
    43: "Mangga",
    44: "Mapilig",
    45: "Mulawin",
    46: "Narra",
    47: "Palawan Ipil",
    48: "Palo-Maria",
    49: "Puso Puso",
    50: "Putat",
    51: "Red Lauan",
    52: "Santol",
    53: "Scramble-Egg",
    54: "Sintores",
    55: "Talisay",
    56: "Tibig",
    57: "Tui",
    58: "Ulayan",
    59: "White Lauan",
    60: "Yakal",
}
